- name: Secure the site with Letsencrypt
  hosts: localhost
  become: true

  # play-level defaults (optional—delete or adjust as you wish)
  vars:
    webroot_path: /var/www/html
    certbot_source_directory: /usr/local/certbot-src
    certbot_executable_path: "{{ certbot_source_directory }}/venv/bin/certbot"

  pre_tasks:
    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: "vars/{{ ansible_hostname }}.yml"

  tasks:
    - name: Install required packages for certbot
      ansible.builtin.apt:
        name:
          - python3-venv
          - gcc
          - libaugeas0
          - libssl-dev
          - libffi-dev
          - ca-certificates
          - openssl
          - git
        state: present

    - name: Clone the certbot source directory
      ansible.builtin.git:
        repo:  https://github.com/certbot/certbot
        dest:  "{{ certbot_source_directory }}"
        depth: 1
        version: v2.8.0
        update: yes

    - name: Create certbot virtualenv
      ansible.builtin.command: python3 tools/venv.py
      args:
        chdir: "{{ certbot_source_directory }}"

    - name: Generate the SSL certificate
      ansible.builtin.command:
        argv:
          - "{{ certbot_executable_path }}"
          - "--nginx"
          - "-d" ; "{{ domain }}"
          - "--non-interactive"
          - "--agree-tos"
          - "--email" ; "{{ email }}"

    - name: Set up automatic renewal
      ansible.builtin.cron:
        name:  Certbot automatic renewal
        job:   "{{ certbot_executable_path }} renew --quiet"
        minute: "11"
        hour:   "11"
