---
# tasks file for fail2ban
- name: Install fail2ban package
  package:
    name: fail2ban
    state: present

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify:
    - Restart fail2ban service
